services:
  - docker

#before_install:
  #- docker build -t ilyanesterow/test -f Dockerfile.dev .

#script:
  #- docker run -e CI=true ilyanesterow/test npm run test

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME
  on: 
    branch: main
  