services:
  - docker

before_install:
  - docker build -t ilyanesterow/test -f Dockerfile.dev .

script:
  - docker run -e CI=true ilyanesterow/test npm run test  -- --coverage

after_success:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - docker build -t web .
  - heroku auth:token
  - heroku container:push web --app $HEROKU_APP_NAME
  - heroku container:release web --app $HEROKU_APP_NAME
 