services:
  - docker

before_install:
  - docker build -t ilyanesterow/test -f Dockerfile.dev .

script:
  - docker run -e CI=true ilyanesterow/test npm run test  -- --coverage

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
  - docker build -t $DOCKER_USERNAME/lakta-prod .
  - docker push $DOCKER_USERNAME/lakta-prod

#deploy:
  #provider: heroku
  #api_key: $HEROKU_API_KEY
  #app: $HEROKU_APP_NAME 
  #on: 
    #branch: main 
  #provider: elasticbeanstalk
  #access_key_id: $AWS_ACCESS_ID
  #secret_access_key: $AWS_SECRET_KEY
  #region: "us-west-2"
  #app: "lakta"
  #env: "Lakta-env-1"
  #bucket_name: "elasticbeanstalk-us-west-2-284065031581"
  #on: 
    #branch: main  
  