services:
  - docker

before_install:
  - docker build -t ilyanesterow/test -f Dockerfile.dev .

script:
  - docker run -e CI=true ilyanesterow/test npm run test  -- --coverage

#after_success:
#  - curl https://cli-assets.heroku.com/install.sh | sh
#  - docker build -t web .
#  - ( echo "$HEROKU_USERNAME" echo "$HEROKU_PASSWORD" ) | heroku login -i
#  - heroku container:login
#  - heroku container:push web
#  - heroku container:release web --app $HEROKU_APP_NAME

#deploy:
  #provider: heroku
  #api_key: $HEROKU_API_KEY
  #app: $HEROKU_APP_NAME 
  #on: 
    #branch: main 
  #provider: elasticbeanstalk
  #access_key_id: $AWS_ACCESS_ID
  #secret_access_key: $AWS_SECRET_KEY
  #region: "us-west-2"
  #app: "lakta"
  #env: "Lakta-env-1"
  #bucket_name: "elasticbeanstalk-us-west-2-284065031581"
  #on: 
    #branch: main  
  