services:
  - docker

before_install:
  - docker build -t ilyanesterow/test -f Dockerfile.dev .

script:
  - docker run -e CI=true ilyanesterow/test npm run test  -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "lakta"
  env: "Lakta-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-284065031581"
  bucket_path: "lakta"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
  #api_key: $HEROKU_API_KEY
  #app: $HEROKU_APP_NAME
  #on: 
   # branch: main
  