services:
  - docker

before_install:
  - docker build -t ilyanesterow/test -f Dockerfile.dev .

script:
  - docker run -e CI=true ilyanesterow/test npm run test  -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh